services:
  - type: web
    name: invite-video-app
    env: python
    buildCommand: bash render-build.sh
    startCommand: gunicorn app:app --worker-class gevent --workers 1 --timeout 300 --keep-alive 5
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false